[package]
name = "html_parse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_parser = "0.6.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }