[package]
name = "rocket-code-gen-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket_codegen = "0.5.0-rc.1"
rocket = "0.5.0-rc.1"