[package]
name = "prom_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket_prometheus = "0.9.0"
rocket = "0.4.10"